const App=(()=>{
 const $=s=>document.querySelector(s);
 const escape=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 function toast(message,type='success'){const box=$('#toast-container');if(!box)return;const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;box.appendChild(el);setTimeout(()=>el.remove(),3000)}
 function songCard(s){const liked=Wishlist.has(s.id);const el=document.createElement('article');el.className='song-card';el.tabIndex=0;el.innerHTML=`<div class="cover-wrap"><img src="${s.cover}" alt="${escape(s.title)} album artwork"><button class="cover-play" data-play="${s.id}" aria-label="Play ${escape(s.title)}">▶</button></div><button class="heart-btn ${liked?'liked':''}" data-like="${s.id}" aria-label="${liked?'Remove':'Add'} ${escape(s.title)} ${liked?'from':'to'} wishlist">${liked?'♥':'♡'}</button><div class="song-info"><strong class="song-title">${escape(s.title)}</strong><span class="song-artist">${escape(s.artist)}</span></div>`;el.querySelector('[data-play]').addEventListener('click',()=>Player.playById(s.id));el.querySelector('[data-like]').addEventListener('click',()=>{const added=Wishlist.toggle(s.id);const b=el.querySelector('[data-like]');b.classList.toggle('liked',added);b.textContent=added?'♥':'♡';b.setAttribute('aria-label',`${added?'Remove':'Add'} ${s.title} ${added?'from':'to'} wishlist`);toast(added?'✓ Song added to wishlist':'✓ Song removed from wishlist')});return el}
 function renderGrid(id,songs){const el=document.getElementById(id);if(!el)return;el.innerHTML='';songs.forEach(s=>el.appendChild(songCard(s)))}
 function recentSongs(){return JSON.parse(localStorage.getItem('pulse_recent')||'[]').map(id=>SONGS.find(s=>s.id===Number(id))).filter(Boolean)}
 function renderHome(){renderGrid('recommended-grid',SONGS.slice(0,6));renderGrid('popular-grid',[...SONGS].sort((a,b)=>b.id%7-a.id%7).slice(0,6));const recent=recentSongs();renderGrid('recent-grid',recent);$('#recent-empty').hidden=recent.length>0;const artists=[...new Map(SONGS.map(s=>[s.artist,s])).values()];const ag=$('#artist-grid');if(ag){ag.innerHTML='';artists.forEach(s=>{const d=document.createElement('div');d.className='artist-card';d.innerHTML=`<div class="artist-avatar">${escape(s.artist.charAt(0))}</div><strong>${escape(s.artist)}</strong><span>${escape(s.genre)} artist</span>`;ag.appendChild(d)})}$('#hero-play')?.addEventListener('click',()=>Player.playById(SONGS[0].id));$('#recommended-next')?.addEventListener('click',()=>location.href='playlist.html?name=Chill%20Vibes')}
 function setupSearch(){const input=$('#search-input');if(!input)return;const section=$('#search-section'),results=$('#search-results'),empty=$('#search-empty'),count=$('#search-count'),clear=$('#clear-search');const run=()=>{const q=input.value.trim().toLowerCase();if(!q){section.hidden=true;return}section.hidden=false;const found=SONGS.filter(s=>[s.title,s.artist,s.album,s.genre].some(v=>v.toLowerCase().includes(q)));results.innerHTML='';found.forEach(s=>results.appendChild(songCard(s)));count.textContent=`${found.length} ${found.length===1?'track':'tracks'}`;empty.hidden=found.length>0};input.addEventListener('input',run);clear?.addEventListener('click',()=>{input.value='';run();input.focus()});$('#focus-search')?.addEventListener('click',()=>{input.focus();input.scrollIntoView({behavior:'smooth',block:'center'})})}
 function renderPlaylist(){const title=$('#playlist-title');if(!title)return;const name=new URLSearchParams(location.search).get('name')||'Chill Vibes';const config=PLAYLISTS[name]||PLAYLISTS['Chill Vibes'];let songs;if(config.favorites)songs=Wishlist.get().map(id=>SONGS.find(s=>s.id===id)).filter(Boolean);else songs=SONGS.filter(s=>config.genres.includes(s.genre));title.textContent=name;$('#playlist-description').textContent=config.description;$('#playlist-count').textContent=`${songs.length} songs`;$('#playlist-cover-big').textContent=name==='Workout'?'⚡':name==='Telugu Hits'?'✦':name==='Lo-Fi'?'▱':name==='Favorites'?'♥':'☾';const list=$('#playlist-tracks');list.innerHTML='';songs.forEach((s,i)=>{const row=document.createElement('div');row.className='track-row';row.innerHTML=`<span class="track-index">${String(i+1).padStart(2,'0')}</span><div class="row-main"><strong>${escape(s.title)}</strong><span>${escape(s.artist)}</span></div><span class="row-muted">${escape(s.album)}</span><span class="row-muted">${escape(s.duration)}</span><div class="row-actions"><button class="mini-btn" data-play="${s.id}" aria-label="Play ${s.title}">▶</button><button class="mini-btn" data-like="${s.id}" aria-label="Toggle wishlist">${Wishlist.has(s.id)?'♥':'♡'}</button></div>`;list.appendChild(row)});if(!songs.length){list.innerHTML='<div class="empty-state compact"><div class="empty-icon">♪</div><h3>This playlist is empty</h3><p>Play some music or save a few songs to fill it up.</p></div>'}list.querySelectorAll('[data-play]').forEach(b=>b.addEventListener('click',()=>Player.playById(Number(b.dataset.play))));list.querySelectorAll('[data-like]').forEach(b=>b.addEventListener('click',()=>{const added=Wishlist.toggle(Number(b.dataset.like));b.textContent=added?'♥':'♡';toast(added?'✓ Song added to wishlist':'✓ Song removed from wishlist')}));$('#playlist-play')?.addEventListener('click',()=>songs.length?Player.playById(songs[0].id):toast('This playlist is empty.','error'));$('#playlist-shuffle')?.addEventListener('click',()=>songs.length?Player.playById(songs[Math.floor(Math.random()*songs.length)].id):toast('This playlist is empty.','error'))}
 function setupGlobal(){document.querySelectorAll('#global-search').forEach(i=>i.addEventListener('keydown',e=>{if(e.key==='Enter'&&i.value.trim())location.href=`index.html#search-section?q=${encodeURIComponent(i.value.trim())}` }));$('#mobile-menu')?.addEventListener('click',()=>$('.sidebar')?.classList.toggle('open'))}
 function init(){if(document.body.dataset.protected==='true'&&!Auth.requireAuth())return;Auth.hydrateProfile();Auth.setupLogin();Auth.setupRegister();if(document.body.dataset.page==='home'){renderHome();setupSearch()}if(document.body.dataset.page==='wishlist')Wishlist.render();if(document.body.dataset.page==='playlist')renderPlaylist();setupGlobal();if(document.getElementById('audio'))Player.setup()}
 return {toast,init};
})();
document.addEventListener('DOMContentLoaded',App.init);
