const Auth = (() => {
 const USERS_KEY='pulse_users', CURRENT_KEY='currentUser';
 const getUsers=()=>JSON.parse(localStorage.getItem(USERS_KEY)||'[]');
 const saveUsers=users=>localStorage.setItem(USERS_KEY,JSON.stringify(users));
 const getCurrent=()=>JSON.parse(localStorage.getItem(CURRENT_KEY)||'null');
 const setCurrent=user=>localStorage.setItem(CURRENT_KEY,JSON.stringify(user));
 const logout=()=>{localStorage.removeItem(CURRENT_KEY);location.href='login.html';};
 const emailOk=e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e);
 const strength=p=>{let n=0;if(p.length>=8)n++;if(/[A-Z]/.test(p))n++;if(/[0-9]/.test(p))n++;if(/[^A-Za-z0-9]/.test(p))n++;return n};
 function requireAuth(){if(document.body.dataset.protected==='true'&&!getCurrent()){location.replace('login.html');return false}return true}
 function hydrateProfile(){const u=getCurrent();if(!u)return;document.querySelectorAll('#profile-name,#header-name').forEach(el=>el.textContent=u.name);document.querySelectorAll('#profile-avatar,#header-avatar').forEach(el=>el.textContent=(u.name||'P').trim().charAt(0).toUpperCase());const logoutBtn=document.getElementById('logout-btn');if(logoutBtn)logoutBtn.addEventListener('click',logout)}
 function setupLogin(){const form=document.getElementById('login-form');if(!form)return;document.querySelectorAll('.password-toggle').forEach(btn=>btn.addEventListener('click',()=>{const input=document.getElementById(btn.dataset.target);input.type=input.type==='password'?'text':'password';btn.textContent=input.type==='password'?'◉':'◌'}));document.querySelectorAll('.social-btn').forEach(btn=>btn.addEventListener('click',()=>showStatus('login-status',`${btn.dataset.social} login is a UI placeholder in this frontend-only demo.`,false)));const forgot=document.getElementById('forgot-link');forgot.addEventListener('click',e=>{e.preventDefault();showStatus('login-status','Password reset is not connected in this demo. Use your registered password.',false)});form.addEventListener('submit',e=>{e.preventDefault();const email=form.email.value.trim().toLowerCase(),pass=form.password.value;clearErrors(form);let valid=true;if(!emailOk(email)){setError('login-email-error','Enter a valid email.');valid=false}if(!pass){setError('login-password-error','Enter your password.');valid=false}if(!valid)return;const user=getUsers().find(u=>u.email===email&&u.password===pass);if(!user){setError('login-password-error','Email or password is incorrect.');return}setCurrent({name:user.name,email:user.email});localStorage.setItem('rememberMe',document.getElementById('remember-me').checked?'true':'false');showStatus('login-status','Login successful. Opening Pulse…',true);setTimeout(()=>location.href='index.html',450)})}
 function setupRegister(){const form=document.getElementById('register-form');if(!form)return;document.querySelectorAll('.password-toggle').forEach(btn=>btn.addEventListener('click',()=>{const input=document.getElementById(btn.dataset.target);input.type=input.type==='password'?'text':'password';btn.textContent=input.type==='password'?'◉':'◌'}));const p=document.getElementById('register-password'),bar=document.getElementById('strength-bar'),label=document.getElementById('strength-label');p.addEventListener('input',()=>{const n=strength(p.value);bar.style.width=`${n*25}%`;label.textContent=['Password strength','Weak','Fair','Good','Strong'][n]});form.addEventListener('submit',e=>{e.preventDefault();clearErrors(form);const name=form.name.value.trim(),email=form.email.value.trim().toLowerCase(),pass=form.password.value,confirm=form.confirm.value,terms=document.getElementById('terms').checked;let valid=true;if(name.length<2){setError('register-name-error','Enter your full name.');valid=false}if(!emailOk(email)){setError('register-email-error','Enter a valid email.');valid=false}if(strength(pass)<2||pass.length<8){setError('register-password-error','Use 8+ characters with a mix of letters, numbers or symbols.');valid=false}if(pass!==confirm){setError('register-confirm-error','Passwords do not match.');valid=false}if(!terms){showStatus('register-status','Please accept the terms to continue.',false);valid=false}if(!valid)return;const users=getUsers();if(users.some(u=>u.email===email)){setError('register-email-error','An account with this email already exists.');return}users.push({name,email,password:pass,createdAt:Date.now()});saveUsers(users);showStatus('register-status','Account created successfully. Redirecting to login…',true);setTimeout(()=>location.href='login.html',650)})}
 function setError(id,msg){const el=document.getElementById(id);if(el)el.textContent=msg;const field=el?.previousElementSibling;if(field?.tagName==='INPUT')field.classList.add('invalid')}
 function clearErrors(form){form.querySelectorAll('.field-error').forEach(e=>e.textContent='');form.querySelectorAll('input').forEach(i=>i.classList.remove('invalid'))}
 function showStatus(id,msg,good){const el=document.getElementById(id);if(el){el.textContent=msg;el.style.color=good?'var(--accent)':'#ff7b86'}}
 return {getCurrent,logout,requireAuth,hydrateProfile,setupLogin,setupRegister,strength};
})();
