const Player = (() => {
 let index=-1,shuffle=false,repeat=false;
 const audio=()=>document.getElementById('audio');
 const stateKey='pulse_player_state';
 const saveState=()=>{if(index<0)return;const s=SONGS[index];localStorage.setItem(stateKey,JSON.stringify({id:s.id,time:audio()?.currentTime||0,volume:audio()?.volume??.8,shuffle,repeat}))};
 const format=t=>{if(!Number.isFinite(t))return'0:00';const m=Math.floor(t/60),s=Math.floor(t%60);return`${m}:${String(s).padStart(2,'0')}`};
 const update=()=>{const a=audio();if(!a)return;const p=document.getElementById('progress-bar');if(p&&a.duration)p.value=(a.currentTime/a.duration)*100;const ct=document.getElementById('current-time'),tt=document.getElementById('total-time');if(ct)ct.textContent=format(a.currentTime);if(tt)tt.textContent=format(a.duration);const pb=document.getElementById('play-btn');if(pb)pb.textContent=a.paused?'▶':'Ⅱ'};
 function renderCurrent(){const s=SONGS[index];if(!s)return;document.getElementById('player-cover').src=s.cover;document.getElementById('player-cover').alt=`${s.title} cover`;document.getElementById('player-title').textContent=s.title;document.getElementById('player-artist').textContent=s.artist;document.getElementById('shuffle-btn')?.classList.toggle('active',shuffle);document.getElementById('repeat-btn')?.classList.toggle('active',repeat);}
 async function load(i,autoplay=true){index=(i+SONGS.length)%SONGS.length;const a=audio();if(!a)return;const s=SONGS[index];a.src=s.audio;a.load();renderCurrent();localStorage.setItem('pulse_last_song',String(s.id));if(autoplay){try{await a.play();App.toast(`▶ Playing “${s.title}”`)}catch{App.toast('Audio is ready — press play to start.','error')}}saveRecent(s.id);}
 async function playById(id){const i=SONGS.findIndex(s=>s.id===Number(id));if(i<0)return;if(index===i){try{await audio().play()}catch{}return}await load(i,true)}
 async function toggle(){const a=audio();if(!a)return;if(index<0){await load(0,true);return}if(a.paused){try{await a.play()}catch{App.toast('Audio could not start.','error')}}else a.pause();update();saveState()}
 function next(){if(index<0)return load(0,true);let i;if(shuffle){i=Math.floor(Math.random()*SONGS.length)}else i=index+1;if(i>=SONGS.length)i=0;load(i,true)}
 function prev(){const a=audio();if(a&&a.currentTime>4){a.currentTime=0;return}load(index-1,true)}
 function saveRecent(id){let r=JSON.parse(localStorage.getItem('pulse_recent')||'[]');r=[Number(id),...r.filter(x=>Number(x)!==Number(id))].slice(0,10);localStorage.setItem('pulse_recent',JSON.stringify(r))}
 function setup(){const a=audio();if(!a)return;document.getElementById('play-btn')?.addEventListener('click',toggle);document.getElementById('next-btn')?.addEventListener('click',next);document.getElementById('prev-btn')?.addEventListener('click',prev);document.getElementById('shuffle-btn')?.addEventListener('click',()=>{shuffle=!shuffle;App.toast(shuffle?'Shuffle on':'Shuffle off');saveState();update()});document.getElementById('repeat-btn')?.addEventListener('click',()=>{repeat=!repeat;App.toast(repeat?'Repeat on':'Repeat off');saveState();update()});document.getElementById('mute-btn')?.addEventListener('click',()=>{a.muted=!a.muted;document.getElementById('mute-btn').textContent=a.muted?'×':'◖';saveState()});const vol=document.getElementById('volume-bar');if(vol){vol.addEventListener('input',e=>{a.volume=Number(e.target.value);a.muted=a.volume===0;saveState()})}const prog=document.getElementById('progress-bar');prog?.addEventListener('input',e=>{if(a.duration)a.currentTime=(Number(e.target.value)/100)*a.duration;update()});a.addEventListener('timeupdate',update);a.addEventListener('loadedmetadata',update);a.addEventListener('play',update);a.addEventListener('pause',()=>{update();saveState()});a.addEventListener('ended',()=>{if(repeat){a.currentTime=0;a.play()}else next()});const st=JSON.parse(localStorage.getItem(stateKey)||'null');const last=Number(localStorage.getItem('pulse_last_song')||0);const target=st?.id||last;if(target){const i=SONGS.findIndex(s=>s.id===target);if(i>=0){index=i;renderCurrent();if(st?.volume!=null){a.volume=st.volume;if(vol)vol.value=st.volume}shuffle=!!st?.shuffle;repeat=!!st?.repeat;update()}}}
 return {setup,playById,toggle,next,prev};
})();
